// note :
// kotasukabumi = 1
// kabupatensukabumi = 2
// kabupatencianjur = 3

const Datas = [
  {
    id: 1,
    namaRS: "RSUD R. Syamsudin SH",
    namaPIPP: "KHAERUNNIDA",
    link: "https://wa.me/08174874323",
    tipe: "B",
    wilayah: "1",
  },
  {
    id: 2,
    namaRS: "RS Bhayangkara Setukpa",
    namaPIPP: "Epi Supyatman",
    link: "https://wa.me/088291313844",
    tipe: "C",
    wilayah: "1",
  },
  {
    id: 3,
    namaRS: "RSI Assyifa",
    namaPIPP: "M. Ihsan Maulana Y.",
    link: "https://wa.me/081213777058",
    tipe: "C",
    wilayah: "1",
  },
  {
    id: 4,
    namaRS: "RS Ridogalih",
    namaPIPP: "Innes Yustiana.A.Md",
    link: "https://wa.me/08111242496",
    tipe: "D",
    wilayah: "1",
  },
  {
    id: 5,
    namaRS: "RS Kartika Kasih",
    namaPIPP: "Mauli Diyanti",
    link: "https://wa.me/081572948469",
    tipe: "C",
    wilayah: "1",
  },
  {
    id: 6,
    namaRS: "RSUD Al Mulk",
    namaPIPP: "Fitryani Intan Putri Utari",
    link: "https://wa.me/085714438360",
    tipe: "D",
    wilayah: "1",
  },
  {
    id: 7,
    namaRS: "Klinik Utama Cemerlang",
    namaPIPP: "Aprida Kusmawati",
    link: "https://wa.me/08119000783",
    tipe: "KU",
    wilayah: "1",
  },
  {
    id: 8,
    namaRS: "Klinik Utama Pradhita",
    namaPIPP: "Novi Daniati",
    link: "https://wa.me/085759990266",
    tipe: "KU",
    wilayah: "1",
  },
  {
    id: 9,
    namaRS: "RSUD Sekarwangi",
    namaPIPP: "Muhammad Rizal Perdana S.ikom",
    link: "https://wa.me/088214554887",
    tipe: "B",
    wilayah: "2",
  },
  {
    id: 10,
    namaRS: "RSUD Palabuhanratu",
    namaPIPP: "YULINDA",
    link: "https://wa.me/081384132626",
    tipe: "C",
    wilayah: "2",
  },
  {
    id: 11,
    namaRS: "RSUD Jampang Kulon",
    namaPIPP: "ISEP APRIANTO, Amd",
    link: "https://wa.me/085603634170",
    tipe: "C",
    wilayah: "2",
  },
  {
    id: 12,
    namaRS: "RS Hermina Sukabumi",
    namaPIPP: "Windu Ginanjar",
    link: "https://wa.me/085723207778",
    tipe: "C",
    wilayah: "2",
  },
  {
    id: 13,
    namaRS: "RS Bhakti Medicare",
    namaPIPP: "Rahayu Ginanjar",
    link: "https://wa.me/089530258258 ",
    tipe: "C",
    wilayah: "2",
  },
  {
    id: 14,
    namaRS: "RS DKH Cibadak",
    namaPIPP: "Nurlaelani Nisfiyani",
    link: "https://wa.me/081211085254",
    tipe: "C",
    wilayah: "2",
  },
  {
    id: 15,
    namaRS: "RS Betha Medika",
    namaPIPP: "Siti Nurul Alfiah",
    link: "https://wa.me/081388960786",
    tipe: "C",
    wilayah: "2",
  },
  {
    id: 16,
    namaRS: "RS Primaya Sukabumi",
    namaPIPP: "RANTI RANDINI ELLENE",
    link: "https://wa.me/085186866050",
    tipe: "C",
    wilayah: "2",
  },
  {
    id: 17,
    namaRS: "RSUD Sagaranten",
    namaPIPP: "Osi Sutra Devani",
    link: "https://wa.me/085749868607",
    tipe: "D",
    wilayah: "2",
  },
  {
    id: 18,
    namaRS: "Klinik Utama Tiara Bunda",
    namaPIPP: "Deuis Suharni",
    link: "https://wa.me/085210385056",
    tipe: "KU",
    wilayah: "2",
  },
  {
    id: 19,
    namaRS: "Klinik Utama Mata KMM",
    namaPIPP: "Ratila Azzahra",
    link: "https://wa.me/081285101198",
    tipe: "KU",
    wilayah: "2",
  },
  {
    id: 20,
    namaRS: "RSUD Sayang",
    namaPIPP: "Direis Rahmatriana",
    link: "https://wa.me/08112292275",
    tipe: "B",
    wilayah: "3",
  },
  {
    id: 21,
    namaRS: "RSUD Cimacan",
    namaPIPP: "LIDYA AGUSTINA",
    link: "https://wa.me/087822654739",
    tipe: "C",
    wilayah: "3",
  },
  {
    id: 22,
    namaRS: "RSU Dr. Hafiz Cianjur",
    namaPIPP: "Putri Fabella Dewi Hauna ",
    link: "https://wa.me/087745465634",
    tipe: "C",
    wilayah: "3",
  },
  {
    id: 23,
    namaRS: "RSUD Pagelaran",
    namaPIPP: "Bintara Widi Yulianto",
    link: "https://wa.me/082258441323",
    tipe: "C",
    wilayah: "3",
  },
  {
    id: 24,
    namaRS: "RS Bhayangkara TK IV",
    namaPIPP: "BRIPTU Ridwan Yudiansyah,S.Farm.,CHRA",
    link: "https://wa.me/'08112229597",
    tipe: "D",
    wilayah: "3",
  },
  {
    id: 25,
    namaRS: "BKPM Cianjur",
    namaPIPP: "Dayat Hardiyanto",
    link: "https://wa.me/'085220054154",
    tipe: "KU",
    wilayah: "3",
  },
  {
    id: 26,
    namaRS: "Klinik Utama Hasna Medika",
    namaPIPP: "Meytha Poniawan, S.M",
    link: "https://wa.me/085930915469",
    tipe: "KU",
    wilayah: "3",
  },
];

export default Datas;
